# Resumen

Este documento presenta una propuesta de diseño de muestreo que debe aplicarse en el desarrollo del XXXXXXX. En este sentido, el documento hace especial énfasis en la aplicación del piloto en su versión 2018 y en la aplicación del estudio principal para 2019 proporcionando algunos concepto básicos de muestreo, definiendo de manera clara el diseño de muestreo propuesto y mostrando a su vez con ejemplos la utilización de este. Adicional a esto, el documento dedica una sección al tamaño de muestra y se presenta un ejercicio de cómo sería dichos tamaños para los países participantes en el XXXXXXX utilizando estimadores complejos e imputando el tamaño de muestra a los países que no participaron en el estudio. Una de las mayores ventajas de esta propuesta es que el equipo de trabajo cuenta con una vasta experiencia práctica en el desarrollo de metodologías de muestreo y tanto la programación de los algoritmos de muestreo como las referencias  bibliográficas de las técnicas utilizadas para la recolección de información primaria son de autoría propia del equipo de trabajo, habiéndose publicado en libros, artículos y paquetes reconocidos y avalados por el `CRAN` del software estadístico `R`.

# Introducción al XXXXXXX 2019

El XXXXXXX (XXXXXXX) es el estudio educativo a gran escala más importante de Latinoamérica y es coordinado por el Laboratorio Latinoamericano de Evaluación de la Calidad de la Educación (LLECE^[ver [LLECE](http://www.unesco.org/new/es/santiago/education/education-assessment-llece/)]), una red de directores nacionales de evaluación educativa de América Latina y el Caribe, coordinada por la Oficina Regional de la UNESCO en Santiago (Chile).

El objetivo de este estudio es brindar información válida y confiable que permita evaluar la calidad de la educación en la región y guiar la toma de decisiones en políticas públicas educativas. Para tal fin, XXXXXXX evalúa el desempeño de los estudiantes en las áreas de lenguaje (lectura y escritura) matemáticas y ciencias, a través de pruebas estandarizadas. Además, aplica cuestionarios de contexto a estudiantes, padres de familia, profesores y rectores, los cuales reúnen información sobre los factores asociados al aprendizaje.

La primera versión del estudio (PXXXXXXX: Primer XXXXXXX) se realizó en 1997 y contó con la participación de 13 países. Este primer estudio evaluó a los estudiantes de tercero y cuarto grado, en las áreas de lectura y matemáticas, y permitió a los países participantes medir el logro de sus estudiantes desde una perspectiva comparativa^[ver [PXXXXXXX website](http://www.unesco.org/new/es/santiago/education/education-assessment-llece/first-regional-comparative-and-explanatory-study/)].

En 2006 se aplicó la segunda versión del estudio (SXXXXXXX: Segundo XXXXXXX), la cual no solo reunió más países y economías (17 en total), sino que también introdujo novedades a la prueba: primero, su población objetivo cambió y se enfocó en los estudiantes de tercero y sexto grado; segundo, tuvo un alcance más amplio al incorporar la evaluación de los aprendizajes en escritura y ciencias; terceroo, aumentó el número de contenidos compartidos de los currículos de la región; y cuarto, incluyó preguntas abiertas en matemáticas y ciencias. Todas estas innovaciones hacen que los resultados de los dos primeros estudios no sean comparables directamente, pero hicieron posible un notorio desarrollo de la prueba^[ver [SXXXXXXX website](http://www.unesco.org/new/es/santiago/education/education-assessment-llece/second-regional-comparative-and-explanatory-study-sXXXXXXX/)].

Finalmente, la terceroa versión del estudio (TXXXXXXX: tercero XXXXXXX) se llevó a cabo en 2013 y evaluó las áreas de lenguaje (lectura y escritura) y matemáticas en los grados terceroo y sexto y el área de ciencias naturales en sexto, en 16 países y economías participantes. Este estudio tuvo también algunas novedades: primero, incluyó preguntas sobre el uso de las tecnologías de la información y la comunicación (TIC); segundo, permitió que, en los cuestionarios de contexto, los países y economías participantes agregaran un módulo con preguntas enfocadas en el contexto nacional; terceroo, modificó los criterios de exclusión para que fueran coherentes con los criterios utilizados en otras pruebas internacionales; y cuarto, incorporó la técnica de valores plausibles^[ver [TXXXXXXX website](http://www.unesco.org/new/es/santiago/education/education-assessment-llece/third-regional-comparative-and-explanatory-study-tXXXXXXX/)].

Además de estas innovaciones, algunas características de TXXXXXXX que sirven como referente para XXXXXXX 2019 corresponden al diseño de la prueba. Esta aplicación del estudio tuvo una prueba en papel para los estudiantes de terceroo y sexto, e incluyó también cuestionarios para padres de familia, profesores y rectores. Los estudiantes de terceroo contestaron una prueba con 15 preguntas de selección múltiple con una duración de 20 minutos; mientras que los estudiantes de sexto contestaron una prueba con 39 preguntas de selección múltiple con una duración de 45 minutos. Los cuestionarios de padres de familia, profesores y rectores estuvieron compuestos por alrededor de 40 preguntas cada uno^[ver: UNESCO – OREALC (2016), Reporte Técnico TXXXXXXX pg. 197]. Finalmente, los resultados de las pruebas de lectura, matemáticas y ciencias se presentaron siguiendo una escala con media 700 y desviación estándar 100.

En conjunto, las tres versiones del estudio han sentado las bases para el desarrollo del Cuarto XXXXXXX (XXXXXXX 2019), el cual se enmarca dentro de los mismos lineamientos ya establecidos: evaluará las mismas áreas y grados que TXXXXXXX y hará uso de una prueba estandarizada en papel y la aplicación de los distintos cuestionarios de contexto mencionados.

Este documento presenta entonces una propuesta muestreo para la aplicación del estudio piloto de XXXXXXX 2019, donde el objetivo principal será evaluar la validez y pertinencia de los ítems. Además, esta es una propuesta para participar activamente en el desarrollo de todas las etapas del estudio y garantizar su ejecución con altos estándares de calidad.

Una ventaja técnica de esta propuesta es que se usaron las bases de datos^[ver [Bases de datos](http://www.unesco.org/new/en/santiago/tXXXXXXX/databases/tXXXXXXX-databases/)] del TXXXXXXX, disponibles en el sitio web de la Unesco, para realizar los cálculos pertinentes a configurar una propuesta más cercana a la realidad del estudio. Todos estos cómputos fueron realizados en el software estadístico `R`, con librerías desarrolladas por el equipo de expertos que presentan esta propuesta, y avaladas directamente por el `Comprehensive R Archive Network - CRAN`.

\newpage
